---
roles:
  - src: https://github.com/punktDe/ansible-proserver-supervisord
    name: supervisord
  - name: system
    src: https://github.com/punktDe/ansible-proserver-system
  - name: nginx
    src: https://github.com/punktDe/ansible-proserver-nginx
  - name: dehydrated
    src: https://github.com/punktDe/ansible-proserver-dehydrated
