---
- name: Create directories for oauth2_proxy
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ oauth2_proxy.prefix.opt }}/bin"
    - "{{ oauth2_proxy.prefix.opt }}/etc"
  when: oauth2_proxy.install == true

- name: Install oauth2_proxy binary
  get_url:
    url: "{{ item.src.url }}"
    checksum: "{{ item.src.checksum }}"
    dest: "{{ item.dest }}"
    mode: a+x
  loop_control:
    label: "{{ item.dest }}"
  with_items:
    - src: "{{ oauth2_proxy.binaries[ansible_system|lower] }}"
      dest: "{{ oauth2_proxy.prefix.opt }}/bin/oauth2_proxy"
  register: oauth2_proxy_install_binary_result
  notify: Restart oauth2_proxy
  when: oauth2_proxy.install == true
