- name: Template systemd service for oauth2_proxy
  ansible.builtin.template:
    src: systemd/oauth2-proxy@.service
    dest: /etc/systemd/system/oauth2-proxy@.service
    owner: root
    mode: "0644"
  register: oauth2_proxy_template_systemd_service_result
  notify: Restart oauth2_proxy
